### ISSUE TITLE
fix(VSCode): localhost connection issue come up when testing through VSCode

### ISSUE THREAD

**Issue by SK-143381** [xability/py_maidr#53]
The following localhost connection error comes up when trying to run MAIDR through VSCode. Settings are both disabled.

![Recording 2024-06-19 at 10 33 57](https://github.com/xability/py_maidr/assets/88380235/acc22c68-184e-4d13-b48d-92c91500c572)

The same code works when running the PyIDLE3.12.2 Shell.

**Comment by jooyoungseo** [comment]
I am closing this issue because clicking `Run` button executes the whole script outside the shell like `python file_name.py` which is not outside intended support. @SK-143381 I will explain later what happened here and why your script did not work in VSCode.
